### ISSUE TITLE
Features to add

### ISSUE THREAD

**Issue by knrt10** [p-society/typeracer-cli#13]
**To-Do**
- [x] Restart mode.
- [x] Request rematch.
- [x] Add more paragraphs.
- [x] Top 10 High scores.
- [x] Add badges {Messi, Ronaldo for legends}
